[workspace]
members = ["crates/ldnddev_theme"]
resolver = "3"

[package]
name = "dd_siteforge"
version = "1.11.0"
edition = "2024"
license = "MIT"

[profile.release]
opt-level = "z" # smaller than "s" (3.4M vs 3.7M)
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
handlebars = "6.3"
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
ratatui = { version = "0.30", default-features = false, features = ["crossterm", "layout-cache"] }
rust-embed = { version = "8", features = ["include-exclude"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
ldnddev_theme = { path = "crates/ldnddev_theme" }
