[package]
name = "dd_siteforge"
version = "1.8.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
handlebars = "6.3"
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
ratatui = "0.29"
rust-embed = { version = "8", features = ["include-exclude"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
